<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    
<?php 

    /**
     *@author Rolando Arriaza
     *@version 1.5 
     *@copyright (c) 2015, Lieison
     */

    set_dependencies(array( "UserController"));
    
    $header = new Http\Header(); //clase header , ver en documentacion
    
    
    if(!Session::GetSession("login")): //verifica si existe sesion 
        if(file_exists("login.php")):
              $header->redirect("login/"); //dado caso no exista retorna a login
        else:
             $header->redirect("../login/"); //dado caso no exista retorna a login
        endif;
            exit();
    endif;
    
    
    //VARIABLES DE SESION , ESTAS VARIABLES SE DECLARAN AL INICIAR EL LOGUEO 
    $SessionUser = Session::GetSession("login");
    $usuario = $SessionUser['user'];
    $rol = $SessionUser['rol'];
    $nombre = $SessionUser['nombre'];
    $mail = $SessionUser['email'];
    $activo = $SessionUser['activo'];
    $id_user = $SessionUser['id'];
    
    //VERIFICAR SI EL AVATAR ESTA VACIO (ASIGNARLE AVATAR EMPTY) O SI EXISTE AVATAR (EN IMAGEN)
    $imagen = UserController::Verify_Avatar();
    
    //EN CASO DE QUE LA PANTALLA ESTE BLOQUEADA REVISAMOS SI LA SESION DE BLOQUEO EXISTE
    //LUEGO DE ESO VERIFICAMOS SI EL BLOQUEO CONTINUA O SE HA DESHABILITADO
     
     if(Session::ExistSession("lock")):
        if(Session::GetSession("lock") == true):
            $header->redirect("lock.php");
        endif; 
    endif;
    
    //VER SI LA CUENTA ACTUAL ESTA ACTIVA
    if($activo == 0):
        $header->redirect("../cuenta_desactivada.php");
        exit();
    endif;
    
    //SI EXISTE UNA REDIRECCION ENTONCES EL SISTEMA REDIRECCIONARA AL LUGAR DESEADO
    if(isset($_REQUEST['redirect'])):
         $header->redirect(FunctionsController::GetUrl($_REQUEST['redirect']));
         exit();
    endif;


    //INGRESA LA RUTA , ESTE CASO SE HA DEJADO COMO RUTA ABSOLUTA , PERO TAMBIEN APLICA RELATIVAS
    $host = null;
    if(!isset($_COOKIES['HOST'])):
        $host =  $_SERVER['HTTP_HOST'];
    else :
        $host = $_COOKIE['HOST'];
    endif;
    
    //AdminHeader::$relative_route =  "http://" . $host  . "/" .$_COOKIE['FOLDER'] . '/Content/Web/'; //DEPRECADO
    AdminHeader::$relative_route = FunctionsController::GetContentUrl("Web/");
    AdminHeader::GetTitle("Lieisoft"); //TITULO INICIAL DEL DASHBOARD
    AdminHeader::GetMeta(); //OBTIENE LOS METAS UTILIZADOS 
    AdminHeader::GetCss();//OBTIENE LAS OJAS DE ESTILO UTILIZADAS
    
    if(isset($_SESSION['page_name'])): //VERIFICA SI EL NOMBRE DE LA PAGINA HA CAMBIADO , APLICA PARA TODAS LAS PAGINAS
        $page_name = $_SESSION['page_name'];
    else:
        $page_name = "Principal"; //DADO CASO NO EXISTA EL NOMBRE DE LA PAGINA SE TOMA COMO PRINCIPAL
    endif;
    
    //OBTENEMOS EL ICONO DEL KIWI :3
    AdminHeader::GetIcon();
    
?>
    
<!-- ESTABLECIENDO EL HEADER  --> 
<script src="../../assets/global/plugins/pace/pace.min.js" type="text/javascript"></script><link href="../../assets/admin/pages/css/blog.css" rel="stylesheet" type="text/css"/><link href="../css/loading-lieison-cms.css" rel="stylesheet" type="text/css"/>
</head>


<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed page-quick-sidebar-over-content page-style-square"> 
    
<?php AdminHeader::GetHiddenData(); ?>   
<input type="hidden" id="rol_value" value="<?php echo $rol; ?>" />
<input type="hidden" id="page_value" value="<?php echo $page_name; ?>" />
<input type="hidden" id="avatar" value="<?php echo $imagen; ?>" />
<input type="hidden" id="id_chat" value="" />
<input type="hidden" id="recive_chat" value="" />
<input type="hidden" id="send_chat_id" value="" />


<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
	<!-- BEGIN HEADER INNER -->
	<div class="page-header-inner">
		<!-- BEGIN LOGO -->
		<div class="page-logo">
			<?php 
                            /*
                             * Logo Lieisoft Esquina superior Izquierda
                             */
                            AdminHeader::GetLogo(177,49);      
                        ?>
			<div class="menu-toggler sidebar-toggler hide">
                            <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
			</div>
		</div>
		<!-- END LOGO -->
		<!-- BEGIN RESPONSIVE MENU TOGGLER -->
		<a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
		</a>
		<!-- END RESPONSIVE MENU TOGGLER -->
		<!-- BEGIN TOP NAVIGATION MENU -->
		<div class="top-menu">
			<ul class="nav navbar-nav pull-right">
                            <!-- CARGA EL SISTEMA DE MENSAJERIA INBOX  -->  
                            <li class="dropdown dropdown-extended dropdown-inbox" id="header_inbox_bar">			 
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                    <i class="icon-envelope-open"></i>
                                    <span id="inbox_count" class="badge badge-active">
                                        <img src="../../admin/img/assert/loading.gif" width="10" height="10" />
                                    </span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li id="inbox_data" class="external">
                                         <!-- DATA DEL INBOX  -->  
                                    </li>
                                    <li>
                                        <ul id="inbox_messages" class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
                                              <!-- MENSAJES  -->  
                                              <br>
                                              <br>
             
                                              <p align="center">
                                                  <img src="../../admin/img/assert/loading.gif" width="200" height="200" />
                                              </p>
                                        </ul>
                                    </li>
                                </ul>
                               
                            </li>
                            <li id="load_task" class="dropdown dropdown-extended dropdown-tasks" id="header_task_bar">			
                                  <!-- CARGA EL SISTEMA DE TAREAS -->
                            </li>    
				<!-- BEGIN USER LOGIN DROPDOWN -->
				<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
				<li class="dropdown dropdown-user">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                        <?php 
                                                /**
                                                 * OBTENEMOS LA IMAGEN DEL USUARIO
                                                 */
                                                AdminHeader::Get_ImgSesion($imagen);
                                        ?>
					<span class="username username-hide-on-mobile">
					<?php 
                                                echo $usuario; //NOMBRE DEL USUARIO 
                                        ?>
                                        </span>
					<i class="fa fa-angle-down"></i>
					</a>
					<?php 
                                                AdminHeader::Get_DropDown(); //OBTENEMOS LAS OPCIONES COMO , PERFIL , CERRAR SESION ETC. 
                                        ?>
				</li>
 
				<!-- END USER LOGIN DROPDOWN -->
				<!-- BEGIN QUICK SIDEBAR TOGGLER -->
				<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
				<li class="dropdown dropdown-quick-sidebar-toggler">
					<a href="javascript:;stop_chat();" class="dropdown-toggle">
					<i class="icon-logout"></i>
					</a>
				</li>
				<!-- END QUICK SIDEBAR TOGGLER -->
			</ul>
                    
                        
		</div>
		<!-- END TOP NAVIGATION MENU -->
	</div>
	<!-- END HEADER INNER -->
</div>
<!-- END HEADER -->
<div class="clearfix">
</div>
<!-- BEGIN CONTAINER -->
<div class="page-container">
	<!-- BEGIN SIDEBAR -->
	<div class="page-sidebar-wrapper">
		<div class="page-sidebar navbar-collapse collapse">
			<ul id="dashboard_sidebar_load" class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
				<!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
                                <?php
                                   
                                    /*SE ACTUALIZO EL SIDEBAR POR AJAX SIDEBAR ...
                                     * 
                                     * id="dashboard_sidebar_load"
                                     * 
                                     * **/
                                ?>
			</ul>
			<!-- END SIDEBAR MENU -->
		</div>
	</div>
	<!-- END SIDEBAR -->
	<!-- BEGIN CONTENT -->
	<div class="page-content-wrapper">
		<div class="page-content">
			<!-- BEGIN PAGE HEADER-->
			<?php 
                            if(isset($_SESSION['title'])): //AGREGA EL TITULO EN LA CABECERA
                                AdminHeader::Get_CMS_Title($_SESSION['title']); 
                            else:
                                if(!isset($_SESSION['DUPLICATE_SESSION'])):
                                    AdminHeader::Get_CMS_Title("Lieisoft Dashboard <b>" . $nombre .  "</b>"); 
                                else:
                                    AdminHeader::Get_CMS_Title("<b>Tú</b> Tienes una <b>Sesion</b> Abierta en otro navegador"); 
                                endif;
                            endif; //EN DADO CASO NO EXISTA LA SESION DE TITULO SE DEFINE POR DEFECTO UNO.
                            
                        ?>
			<div class="page-bar">
				<?php 
                                     if(isset($_SESSION['home'])): // DEFINIR EL HOME 
                                         AdminHeader::Get_Sublinks("Home" , $_SESSION['home']);
                                     else:
                                         AdminHeader::Get_Sublinks("Home" , $usuario);
                                     endif; // 
                                     
                                ?>
			</div>          
                    <?php include 'view_task.php' ?>
                </div>
            
</div>
        </div>
<!-- END CONTAINER -->


<!-- BEGIN QUICK SIDEBAR -->
<a href="javascript:;" class="page-quick-sidebar-toggler"><i class="icon-close"></i></a>
<div class="page-quick-sidebar-wrapper">
    <div class="page-quick-sidebar">
        <div class="nav-justified">
            <ul class="nav nav-tabs nav-justified">
                <li class="active">
                    <a href="#quick_sidebar_tab_1" data-toggle="tab">
                        Chat 
                        <span id="chat_count" class="badge badge-danger">
                             <!-- CARGAMOS LA CANTIDAD DE CHAT ABIERTOS  -->
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#quick_sidebar_tab_2" data-toggle="tab">
                     NULL   <span class="badge badge-success">7</span>
                    </a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                     NULL<i class="fa fa-angle-down"></i>
                   </a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active page-quick-sidebar-chat" id="quick_sidebar_tab_1">
                    <div id="user_chat" class="page-quick-sidebar-chat-users" data-rail-color="#ddd" data-wrapper-class="page-quick-sidebar-list">
                            <!-- CARGAMOS LOS USUARIOS QUE ESTAN CHATEANDO -->
                           
                    </div>
                    <div class="page-quick-sidebar-item">

                          <div class="page-quick-sidebar-chat-user">
                            <div class="page-quick-sidebar-nav">
                                <a href="javascript:;stop_chat();" class="page-quick-sidebar-back-to-list"><i class="icon-arrow-left"></i>Atras</a>
                                <embed src="http://soundbible.com/mp3/A-Tone-His_Self-1266414414.mp3" autostart="false" width="0" height="0" id="sound1" enablejavascript="true">
                            </div>
                            <div id="chat_messages" class="page-quick-sidebar-chat-user-messages">
                                 <!-- CARGAREMOS LOS MENSAJES DEL USUARIO EN TERMINOS DE CHAT -->
                            </div>
                            <div class="page-quick-sidebar-chat-user-form">
                                <div class="input-group">
                                    <input id="txt_message" type="text" class="form-control" placeholder="Escribe un mensaje ...">
                                    <div class="input-group-btn">
                                        <button type="button" class="btn blue"><i class="icon-paper-clip"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane page-quick-sidebar-alerts" id="quick_sidebar_tab_2">
                    <div class="page-quick-sidebar-alerts-list">
                        <h3 class="list-heading">General</h3>
                        <ul class="feeds list-items">
                            <li>
                                <div class="col1">
                                    <div class="cont">
                                        <div class="cont-col1">
                                            <div class="label label-sm label-info">
                                                <i class="fa fa-check"></i>
                                            </div>
                                        </div>
                                        <div class="cont-col2">
                                            <div class="desc">
                                                You have 4 pending tasks. <span class="label label-sm label-warning ">
                                                Take action <i class="fa fa-share"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col2">
                                    <div class="date">
                                        Just now
                                    </div>
                                </div>
                            </li>
                            <li>
                                <a href="#">
                                    <div class="col1">
                                        <div class="cont">
                                            <div class="cont-col1">
                                                <div class="label label-sm label-success">
                                                    <i class="fa fa-bar-chart-o"></i>
                                                </div>
                                            </div>
                                            <div class="cont-col2">
                                                <div class="desc">
                                                    Finance Report for year 2013 has been released.
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col2">
                                        <div class="date">
                                            20 mins
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <div class="col1">
                                    <div class="cont">
                                        <div class="cont-col1">
                                            <div class="label label-sm label-danger">
                                                <i class="fa fa-user"></i>
                                            </div>
                                        </div>
                                        <div class="cont-col2">
                                            <div class="desc">
                                                You have 5 pending membership that requires a quick review.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col2">
                                    <div class="date">
                                        24 mins
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="col1">
                                    <div class="cont">
                                        <div class="cont-col1">
                                            <div class="label label-sm label-info">
                                                <i class="fa fa-shopping-cart"></i>
                                            </div>
                                        </div>
                                        <div class="cont-col2">
                                            <div class="desc">
                                                New order received with <span class="label label-sm label-success">
                                                Reference Number: DR23923 </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col2">
                                    <div class="date">
                                        30 mins
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="col1">
                                    <div class="cont">
                                        <div class="cont-col1">
                                            <div class="label label-sm label-success">
                                                <i class="fa fa-user"></i>
                                            </div>
                                        </div>
                                        <div class="cont-col2">
                                            <div class="desc">
                                                You have 5 pending membership that requires a quick review.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col2">
                                    <div class="date">
                                        24 mins
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="col1">
                                    <div class="cont">
                                        <div class="cont-col1">
                                            <div class="label label-sm label-info">
                                                <i class="fa fa-bell-o"></i>
                                            </div>
                                        </div>
                                        <div class="cont-col2">
                                            <div class="desc">
                                                Web server hardware needs to be upgraded. <span class="label label-sm label-warning">
                                                Overdue </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col2">
                                    <div class="date">
                                        2 hours
                                    </div>
                                </div>
                            </li>
                            <li>
                                <a href="#">
                                    <div class="col1">
                                        <div class="cont">
                                            <div class="cont-col1">
                                                <div class="label label-sm label-default">
                                                    <i class="fa fa-briefcase"></i>
                                                </div>
                                            </div>
                                            <div class="cont-col2">
                                                <div class="desc">
                                                    IPO Report for year 2013 has been released.
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col2">
                                        <div class="date">
                                            20 mins
                                        </div>
                                    </div>
                                </a>
                            </li>
                        </ul>
                        <h3 class="list-heading">System</h3>
                        <ul class="feeds list-items">
                            <li>
                                <div class="col1">
                                    <div class="cont">
                                        <div class="cont-col1">
                                            <div class="label label-sm label-info">
                                                <i class="fa fa-check"></i>
                                            </div>
                                        </div>
                                        <div class="cont-col2">
                                            <div class="desc">
                                                You have 4 pending tasks. <span class="label label-sm label-warning ">
                                                Take action <i class="fa fa-share"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col2">
                                    <div class="date">
                                        Just now
                                    </div>
                                </div>
                            </li>
                            <li>
                                <a href="#">
                                    <div class="col1">
                                        <div class="cont">
                                            <div class="cont-col1">
                                                <div class="label label-sm label-danger">
                                                    <i class="fa fa-bar-chart-o"></i>
                                                </div>
                                            </div>
                                            <div class="cont-col2">
                                                <div class="desc">
                                                    Finance Report for year 2013 has been released.
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col2">
                                        <div class="date">
                                            20 mins
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <div class="col1">
                                    <div class="cont">
                                        <div class="cont-col1">
                                            <div class="label label-sm label-default">
                                                <i class="fa fa-user"></i>
                                            </div>
                                        </div>
                                        <div class="cont-col2">
                                            <div class="desc">
                                                You have 5 pending membership that requires a quick review.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col2">
                                    <div class="date">
                                        24 mins
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="col1">
                                    <div class="cont">
                                        <div class="cont-col1">
                                            <div class="label label-sm label-info">
                                                <i class="fa fa-shopping-cart"></i>
                                            </div>
                                        </div>
                                        <div class="cont-col2">
                                            <div class="desc">
                                                New order received with <span class="label label-sm label-success">
                                                Reference Number: DR23923 </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col2">
                                    <div class="date">
                                        30 mins
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="col1">
                                    <div class="cont">
                                        <div class="cont-col1">
                                            <div class="label label-sm label-success">
                                                <i class="fa fa-user"></i>
                                            </div>
                                        </div>
                                        <div class="cont-col2">
                                            <div class="desc">
                                                You have 5 pending membership that requires a quick review.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col2">
                                    <div class="date">
                                        24 mins
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="col1">
                                    <div class="cont">
                                        <div class="cont-col1">
                                            <div class="label label-sm label-warning">
                                                <i class="fa fa-bell-o"></i>
                                            </div>
                                        </div>
                                        <div class="cont-col2">
                                            <div class="desc">
                                                Web server hardware needs to be upgraded. <span class="label label-sm label-default ">
                                                Overdue </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col2">
                                    <div class="date">
                                        2 hours
                                    </div>
                                </div>
                            </li>
                            <li>
                                <a href="#">
                                    <div class="col1">
                                        <div class="cont">
                                            <div class="cont-col1">
                                                <div class="label label-sm label-info">
                                                    <i class="fa fa-briefcase"></i>
                                                </div>
                                            </div>
                                            <div class="cont-col2">
                                                <div class="desc">
                                                    IPO Report for year 2013 has been released.
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col2">
                                        <div class="date">
                                            20 mins
                                        </div>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="tab-pane page-quick-sidebar-settings" id="quick_sidebar_tab_3">
                    <div class="page-quick-sidebar-settings-list">
                        <h3 class="list-heading">General Settings</h3>
                        <ul class="list-items borderless">
                            <li>
                                Enable Notifications <input type="checkbox" class="make-switch" checked data-size="small" data-on-color="success" data-on-text="ON" data-off-color="default" data-off-text="OFF">
                            </li>
                            <li>
                                Allow Tracking <input type="checkbox" class="make-switch" data-size="small" data-on-color="info" data-on-text="ON" data-off-color="default" data-off-text="OFF">
                            </li>
                            <li>
                                Log Errors <input type="checkbox" class="make-switch" checked data-size="small" data-on-color="danger" data-on-text="ON" data-off-color="default" data-off-text="OFF">
                            </li>
                            <li>
                                Auto Sumbit Issues <input type="checkbox" class="make-switch" data-size="small" data-on-color="warning" data-on-text="ON" data-off-color="default" data-off-text="OFF">
                            </li>
                            <li>
                                Enable SMS Alerts <input type="checkbox" class="make-switch" checked data-size="small" data-on-color="success" data-on-text="ON" data-off-color="default" data-off-text="OFF">
                            </li>
                        </ul>
                        <h3 class="list-heading">System Settings</h3>
                        <ul class="list-items borderless">
                            <li>
                                Security Level
                                <select class="form-control input-inline input-sm input-small">
                                    <option value="1">Normal</option>
                                    <option value="2" selected>Medium</option>
                                    <option value="e">High</option>
                                </select>
                            </li>
                            <li>
                                Failed Email Attempts <input class="form-control input-inline input-sm input-small" value="5"/>
                            </li>
                            <li>
                                Secondary SMTP Port <input class="form-control input-inline input-sm input-small" value="3560"/>
                            </li>
                            <li>
                                Notify On System Error <input type="checkbox" class="make-switch" checked data-size="small" data-on-color="danger" data-on-text="ON" data-off-color="default" data-off-text="OFF">
                            </li>
                            <li>
                                Notify On SMTP Error <input type="checkbox" class="make-switch" checked data-size="small" data-on-color="warning" data-on-text="ON" data-off-color="default" data-off-text="OFF">
                            </li>
                        </ul>
                        <div class="inner-content">
                            <button class="btn btn-success"><i class="icon-settings"></i> Save Changes</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- BEGIN FOOTER -->
<div class="page-footer">
	<div class="page-footer-inner">
		 <?php AdminHeader::GetCopyRight(); ?>
	</div>
	<div class="scroll-to-top">
		<i class="icon-arrow-up"></i>
	</div>
</div>

<?php AdminHeader::GetJs(); ?>

<script src='js/TaskView.js'></script> 

<script>
    
    
  jQuery(document).ready(function() {    
      
   <?php
        /*INICIA TODOS LOS AJAX COMO INBOX , NOTIFICACIONES ETC*/
        AdminHeader::GetJsSystemLoad();
    
   ?> 
           
      
   //init template core
   Metronic.init(); 
   Layout.init(); 
   QuickSidebar.init(); 
   Demo.init(); 
   Index.init();   

    //app init lieisoft
   TaskInit.init();    

});
</script>
<!-- END JAVASCRIPTS -->

</body>
<!-- END BODY -->
</html>