<style>
  .class_tr_bitacora {
        width: 100%;
        
  }
  .class_tbody_bitacora
  {
    overflow-y: scroll;
    overflow-wrap: scroll;
    height: 430px;
    width: 95%;
    position: absolute;
  }
  
</style>


<script>$('#id_title').html('<p><b>PRUEBA_MASCARA</b>&nbsp&nbsp <a class="btn blue"  href="http://localhost/LieisonCMS/0/admin/sales/dashboard_edit_prospecto.php?id=32"><i class="fa fa-pencil"></i></a> <small>(Perfil Completado:  28.57%)</small></p>');</script>

<div class="row">
<div class="col-md-6 ">
<div class="portlet box blue">
<div class="portlet-title">
<div class="caption">
  <i class="fa fa-globe"></i> Direccion 
</div>
<div class="tools">

</div>
</div>
<div class="portlet-body form">
    <div class="form-body"><i class="fa fa-map-marker"></i><b>Direccion: </b>Acevedo 75, Buenos Aires, Argentina</div><div class="form-body"><i class="fa fa-map-marker"></i> <b>Direccion 2: </b></div><div class="form-body"><i class="fa fa-globe"></i> <b>Provincia : </b><b>&nbsp&nbsp&nbsp&nbsp  <i class="fa fa-globe"></i> Ciudad: </b><b>&nbsp&nbsp&nbsp&nbsp  <i class="fa fa-globe"></i> Pais: </b></div>
</div>
</div>
				
<div class="portlet box red">
    <div class="portlet-title">
		<div class="caption">
                   <i class="fa fa-building-o"></i> Informacion Del Prospecto
		</div>
						
    </div>
	<div class="portlet-body form">
		<div class="form-body"><i class="fa fa-building-o"></i>&nbsp&nbsp <b>Nombre:</b> PRUEBA_MASCARA<br><br><i class="fa fa-building-o"></i>&nbsp&nbsp <b>Telefono:</b> (503) 22625<br><br><i class="fa fa-building-o"></i>&nbsp&nbsp <b>Fax:</b> <br><br><i class="fa fa-building-o"></i>&nbsp&nbsp <b>Fecha de Entrada:</b> 2015-05-16<br><br><div id="prospect_estado"><i class="fa fa-building-o"></i>&nbsp&nbsp <b>Estado:</b> Activo &nbsp&nbsp&nbsp <input class='btn green' type='button' onclick='ProspectActivate(0 ,32);' value='Desactivar' id='cmd_estado' /></div><br><br><div id="meta_estado"><i class="fa fa-building-o"></i>&nbsp&nbsp <b>Arranque Del Prospecto:</b> No iniciado &nbsp&nbsp&nbsp <input class='btn green' type='button' onclick='ProspectInitProcess(0 ,32);' value='Iniciar Proceso' id='cmdmeta_estado' /></div></div>
	</div>
</div>
<div class="portlet box blue">
	<div class="portlet-title">
		<div class="caption">
                    <i class="fa fa-share-square-o"></i>  Redes Sociales
		</div>
							
</div>
    <div class="portlet-body form">
         <form class="form-horizontal" role="form">
              <div class="form-body"><i  class="fa fa-globe"></i>&nbsp&nbsp<b>Pagina Web: </b><a target="_blank" href=""></a><br><br><i class="fa fa-facebook"></i>&nbsp&nbsp<b>Facebook: </b><a target="_blank" href=""></a><br><br><i class="fa fa-twitter"></i>&nbsp&nbsp<b>Twitter: </b><a target="_blank" href="https://twitter.com/">@</a><br></div>
         </form>
    </div>
</div>
				<div class="portlet box green">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-book"></i> Notas
							</div>
							
						</div>
						<div class="portlet-body form">
                                                    <form class="form-horizontal" role="form">
                                                        <div id="id_notes" class="form-body"><b>No Existen notas</b></div><div class="form-actions"><div class="row"><div id="id_notes_actions" class="col-md-offset-4 col-md-8"><button type="button" onclick="ProspectEditNotes(32);" class="btn blue">Agregar Notas </button></div></div></div>
                                                     </form>
						</div>
					</div>
				</div>
				<div class="col-md-6 ">
					<div class="portlet box green ">
						<div class="portlet-title">
							<div class="caption" id='bitacora_reload'>
								<i class="fa fa-book"></i> Bitacora <span class='badge' id='bitacora_counter'>0</span>
							</div>
                                                 <div class="tools">
                                                    
                                                </div>           
						</div>
						<div class="portlet-body form">
                                                    <input type='hidden' id='BitacoraTypes' value='[{"id":"0","title":"Sistema"},{"id":"1","title":"Nulo"}]' /><div class="form-body"><div class="alert alert-danger" role="alert"><i class="fa fa-exclamation-triangle"></i><span>&nbsp&nbsp<b>NO SE HA INICIADO LA BITACORA</b>&nbsp&nbsp<img src="../img/assert/flechaderecha_naranja.png" width="50" height="20" />&nbsp&nbsp&nbsp<b>INICIE EL PROCESO</b> </span></div></div>  
                                                </div>
					</div>
					<!-- END SAMPLE FORM PORTLET-->
					<!-- BEGIN SAMPLE FORM PORTLET-->
					<div class="portlet box blue ">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-phone"></i> Contactos 
							</div>
							<div class="tools">
								<button type="button" onclick="NewContact('32');" class="btn blue"><i class="fa fa-plus"></i></button>
							</div>
						</div>
						<div class="portlet-body form">
							
								<div class="form-body"><div class="alert alert-danger" role="alert"><i class="fa fa-exclamation-triangle"></i><span>&nbsp&nbsp<b>NO EXISTEN CONTACTOS </b>&nbsp&nbsp<img src="../img/assert/flechaderecha_naranja.png" width="50" height="20" />&nbsp&nbsp&nbsp<button type="button" onclick="NewContact('32');" class="btn blue"><i class="fa fa-plus"></i></button></span></div></div></table><div class="form-actions">
							
						</div>
					</div>
		
					</div>
				</div>
			</div>
